# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- Notes
- blog
- categories.md
- Makefile

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://dianekaneosteopath.com'
baseurl: ''
title: 'Diane Kane Osteopathy Wrexham'
description: 'Osteopathy and Cranial Osteopathy in Wrexham with Diane Kane, Treating since 1996'
permalink: pretty
logo: "../images/logo2.png"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: ../favicon/favicon-16x16.png
  32: ../favicon/favicon-32x32.png
  192: ../favicon/android-chrome-192x192.png
  512: ../favicon/android-chrome-512x512.png

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About Osteopathy
  url: /osteopathy
- title: Privacy
  url: /privacy
- title: Contact
  url: /contact

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
